#! /bin/sh

bspc config border_width        1
bspc config window_gap          20
bspc config top_padding         0
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false
bspc config click_to_focus          true
bspc config ignore_ewmh_focus       true 

bspc config remove_disabled_monitors true 
bspc config remove_unplugged_monitors true

bspc config normal_border_color '#282a36'
bspc config focused_border_color '#527fc1'
bspc config presel_feedback_color '#7b7bbc'

bspc rule -a Nightly:Navigator state=tiled

export QT_QPA_PLATFORMTHEME=gtk2
export _JAVA_AWT_WM_NONREPARENTING=1
export LD_PRELOAD="/home/fuego/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0"

sxhkd &
dunst &

killall redshift &> /dev/null
redshift &> /dev/null &

$HOME/.core/screens.sh 
compton --config "$HOME/.config/compton/compton.conf" -b
