#! /bin/sh

bspc config border_width        3
bspc config window_gap          20
bspc config top_padding         5
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false
bspc config click_to_focus          true
bspc config ignore_ewmh_focus       true 

bspc config remove_disabled_monitors true 
bspc config remove_unplugged_monitors true

bspc config normal_border_color '#2b263a'
bspc config focused_border_color '#8585f5'
bspc config presel_feedback_color '#91a9ff'

export QT_QPA_PLATFORMTHEME=gtk2
export _JAVA_AWT_WM_NONREPARENTING=1

sxhkd &
dunst &

killall redshift &> /dev/null
redshift &> /dev/null &

/home/fuego/.core/audio/venv/bin/python /home/fuego/.core/audio/pulse-volume-watcher.py | xob &> /dev/null &

$HOME/.core/screens
