#! /bin/sh

bspc config border_width        3
bspc config window_gap          20
bspc config top_padding         5
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      0

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false
bspc config click_to_focus          true
bspc config ignore_ewmh_focus       true 

bspc config remove_disabled_monitors true 
bspc config remove_unplugged_monitors true

bspc config focused_border_color '#1E1E2E'
bspc config normal_border_color '#181825'
bspc config active_border_color '#181825'
bspc config presel_feedback_color '#cba6f7'

xsetroot -cursor_name left_ptr

sxhkd -m 1 &
dunst &
$HOME/.core/firborder &

$HOME/.core/screens
