#! /bin/bash

# Storage of the xrandr
xrandr="$(xrandr)"
echo $xrandr > $HOME/.core/.cache/xrandr

# Intel drivers
intern="eDP-1"

# NVIDIA drivers
if echo $randr | grep -q "eDP-1-1"; then
    intern="eDP-1-1"
fi

killall -q picom

bspc monitor $intern -n $intern

external_regex="[^e]DP-(\S*) connected"
if [[ $xrandr =~ $external_regex ]]
then
    mons -e right

    extern="DP-${BASH_REMATCH[1]}"
    bspc monitor $extern -n $extern
    bspc desktop 1 -m $extern
    bspc desktop 2 -m $extern
    bspc desktop 3 -m $extern
    bspc desktop 4 -m $extern
    bspc desktop 5 -m $extern
    bspc desktop 6 -m $extern
    bspc desktop 7 -m $extern
    bspc desktop Desktop -r
    bspc monitor $extern -d 1 2 3 4 5 6
    bspc monitor $intern -d 7 8 9 10
    bspc desktop -f 1
else
    mons -o
    bspc monitor $intern -o 1 2 3 4 5 6 7 8 9
    bspc monitor $intern -n $intern -d 1 2 3 4 5 6 7 8 9

    monitors="$(bspc query -M --names)"
    for monitor in $monitors
    do
      if [[ $monitor != $intern ]]
      then
        bspc monitor $monitor -r
      fi
    done

    bspc desktop -f 1
fi

bspc wm -o

feh --bg-scale ~/Pictures/wallpaper.png
$HOME/.config/polybar/start.sh
picom --config "$HOME/.config/picom/picom.conf" --experimental-backends -b
