#! /bin/sh

# Intel drivers
extern="HDMI1"
intern="eDP1"

# NVIDIA drivers
if xrandr | grep -q "HDMI-1-1"; then
    extern="HDMI-1-1"
    intern="eDP-1-1"
fi

bspc monitor $intern -n $intern

if xrandr | grep -q "$extern disconnected"; then
    mons -o
    bspc monitor $intern -n $intern -d term web code chrome notes design slack other1 music
    bspc monitor $extern -r
    bspc desktop -f term
else
    mons -s
    bspc desktop Desktop -r
    bspc monitor $extern -n $extern -d term web code chrome notes design slack other1 music
    bspc monitor $intern -r
    bspc desktop -f term
fi

bspc wm -o

feh --bg-scale ~/Pictures/wallpaper.png &
$HOME/.config/polybar/start.sh

