#! /bin/sh

# Storage of the xrandr
xrandr > $HOME/.core/.cache/xrandr


# Intel drivers
extern="HDMI-1"
intern="eDP-1"

# NVIDIA drivers
if cat $HOME/.core/.cache/xrandr | grep -q "HDMI-1-1"; then
    extern="HDMI-1-1"
    intern="eDP-1-1"
fi

killall picom;

bspc monitor $intern -n $intern

if cat $HOME/.core/.cache/xrandr | grep -q "$extern disconnected"; then
    mons -o
    bspc monitor $intern -o term web code chrome notes design slack other1 music
    bspc monitor $intern -n $intern -d term web code chrome notes design slack other1 music
    bspc monitor $extern -r
    bspc desktop -f term
else
    if xrandr --props | grep "00ffffffffffff0026cd46662e090000"; then
        $HOME/.core/dual_screen_work.sh
    else
        $HOME/.core/dual_screen.sh
    fi
    bspc monitor $extern -n $extern
    bspc desktop term -m $extern
    bspc desktop web -m $extern
    bspc desktop code -m $extern
    bspc desktop chrome -m $extern
    bspc desktop notes -m $extern
    bspc desktop design -m $extern
    bspc desktop other1 -m $extern
    bspc desktop music -m $extern
    bspc desktop Desktop -r
    bspc monitor $extern -d term web code chrome notes design other1 music
    bspc monitor $intern -d slack other2 other3
    bspc desktop -f term
fi

bspc wm -o

feh --bg-scale ~/Pictures/wallpaper.png
$HOME/.config/polybar/start.sh
picom --config "$HOME/.config/picom/picom.conf" -b
