#! /bin/sh

bspc config border_width        1
bspc config window_gap          20
bspc config top_padding         0
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      5

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	false
bspc config pointer_follows_focus 	false
bspc config click_to_focus          	true	

bspc config center_pseudo_tiled  true

bspc config normal_border_color '#282a36'
bspc config focused_border_color '#527fc1'
bspc config presel_feedback_color '#ffac8d'

extern=DP1
intern=eDP1

if xrandr | grep "$extern disconnected"; then
    xrandr --output "$extern" --off --output "$intern" --auto
    bspc monitor $intern -n $intern -d term web code chrome other other mail music
    bspc monitor $extern -r
else
    xrandr --output "$intern" --off --output "$extern" --auto
    bspc monitor $extern -n $extern  -d term web code chrome other other mail music
    bspc monitor $intern -r
fi

bspc rule -a Thunderbird desktop=^7 follow=on
bspc rule -a Firefox desktop=^2 follow=on
bspc rule -a Spotify desktop=^8 follow=on
bspc rule -a Chromium-browser desktop=^4 follow=on
bspc rule -a keepassxc state=floating center=true

sxhkd &
dunst &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/Pictures/wallpaper.jpg &
$HOME/.config/polybar/start.sh &
compton --config "$HOME/.config/compton/compton.conf" -b &
